#!/usr/bin/python3

import json
import requests

r = requests.get(url = "http://localhost:1474/info")

try:
    data = r.json()
    print(json.dumps(data, indent=4, sort_keys=True))
except:
    print(r.text)
